// <auto-generated />
namespace DbLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class IdentNumber : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IdentNumber));
        
        string IMigrationMetadata.Id
        {
            get { return "201410100629229_IdentNumber"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
